const jsLine = require('../index.js')

console.log(jsLine.getLineNum())
console.log(jsLine.getLineNum())
console.log(jsLine.getLineNum())
console.log(jsLine.getLineNum())
console.log(jsLine.getLineNum())
console.log(jsLine.getLineNum())
console.log(jsLine.getLineNum())
console.log(jsLine.getLineNum())